### ISSUE TITLE
Appender for log4j 2

### ISSUE THREAD

**Issue by estliberitas** [stackify/stackify-log-log4j12#1]
Hello! I wonder if appender for log4j v2 will be released soon?

**Comment by eric-martin** [comment]
We don't have this planned yet but should be a fairly simple task. Let me take a look.

**Comment by eric-martin** [comment]
This is currently in progress. I'm testing the implementation now.

**Comment by eric-martin** [comment]
stackify-log-log4j2 v1.0.0 is available. Let me know if you have any questions. Thanks.
https://github.com/stackify/stackify-log-log4j2
