### ISSUE TITLE
Play framework 1.4.2 hangs forever on process exit

### ISSUE THREAD

**Issue by romanr** [stackify/stackify-log-log4j12#4]
Play framework 1.4.2 hangs when executing `evolutions:apply`
`play run`, `play start`, even `play evolutions` work.

On Java 7.

log4j configuration:

```
log4j.rootLogger=INFO, STACKIFY
log4j.logger.play=INFO

log4j.appender.STACKIFY=com.stackify.log.log4j12.StackifyLogAppender
log4j.appender.STACKIFY.apiKey=123asdf
log4j.appender.STACKIFY.application=App
log4j.appender.STACKIFY.environment=${play.id}

```

application.conf:

`application.log.path=/log4j.properties`

dependencies.yml:

`- com.stackify -> stackify-log-log4j12 [1.1.8,)
`
command:

```
$ play evolutions:apply

~ Connected to jdbc:postgresql://localhost/app
~ 'App' Application revision is 113 [3313961] and 'App' Database revision is 113 [3313961]
~
~ Your database default is up to date for App
~

```

At this point the process hangs forever. Does not exit.

We tried logging with Syslog, Logstash-gelf, Logentries,Sumologic Log4j appenders that use TCP and never had any issues.
Only with Logentries Log4j appender.

Pelase help!

**Comment by eric-martin** [comment]
We will take a look.
