### ISSUE TITLE
Is it possible to use the appender for a desktop application with prefix

### ISSUE THREAD

**Issue by stk-code** [stackify/stackify-log-log4j12#6]
I added the appender to the log4j logger of my desktop application,  however prefix does not receive any message. Is it anyhow possible?

**Comment by eric-martin** [comment]
For Prefix, you don't need to use our appender. We automatically instrument log4j and will display the log messages inside the traces.

If you are using Retrace, then you can use the appender to automatically send errors and logs to Stackify.
